version: '2'
services:
  client:
    build:
      context: ../../
      dockerfile: infra/client/Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ../../codebase/client:/home/app/client
      - /home/app/client/node_modules
    command: bash -c "yarn install && yarn start"
